export interface PlantInterface {
  panda_plant: number;
  aloe: number;
  asparagus_fern: number;
  alocasia: number;
  banana_tree: number;
}

export const initialData: PlantInterface[] = [
  {
    panda_plant: 1,
    aloe: 2,
    asparagus_fern: 3,
    alocasia: 2,
    banana_tree: 7,
  },
  {
    panda_plant: 5,
    aloe: 3,
    asparagus_fern: 9,
    alocasia: 9,
    banana_tree: 10,
  },
  {
    panda_plant: 2,
    aloe: 7,
    asparagus_fern: 5,
    alocasia: 9,
    banana_tree: 3,
  },
  {
    panda_plant: 10,
    aloe: 6,
    asparagus_fern: 8,
    alocasia: 6,
    banana_tree: 8,
  },
  {
    panda_plant: 1,
    aloe: 4,
    asparagus_fern: 2,
    alocasia: 8,
    banana_tree: 9,
  },
  {
    panda_plant: 1,
    aloe: 10,
    asparagus_fern: 8,
    alocasia: 4,
    banana_tree: 5,
  },
  {
    panda_plant: 1,
    aloe: 2,
    asparagus_fern: 3,
    alocasia: 2,
    banana_tree: 7,
  },
  {
    panda_plant: 5,
    aloe: 3,
    asparagus_fern: 9,
    alocasia: 9,
    banana_tree: 10,
  },
  {
    panda_plant: 2,
    aloe: 7,
    asparagus_fern: 5,
    alocasia: 9,
    banana_tree: 3,
  },
  {
    panda_plant: 10,
    aloe: 6,
    asparagus_fern: 8,
    alocasia: 6,
    banana_tree: 8,
  },
  {
    panda_plant: 1,
    aloe: 4,
    asparagus_fern: 2,
    alocasia: 8,
    banana_tree: 9,
  },
  {
    panda_plant: 1,
    aloe: 10,
    asparagus_fern: 8,
    alocasia: 4,
    banana_tree: 5,
  },
  {
    panda_plant: 1,
    aloe: 2,
    asparagus_fern: 3,
    alocasia: 2,
    banana_tree: 7,
  },
  {
    panda_plant: 5,
    aloe: 3,
    asparagus_fern: 9,
    alocasia: 9,
    banana_tree: 10,
  },
  {
    panda_plant: 2,
    aloe: 7,
    asparagus_fern: 5,
    alocasia: 9,
    banana_tree: 3,
  },
  {
    panda_plant: 10,
    aloe: 6,
    asparagus_fern: 8,
    alocasia: 6,
    banana_tree: 8,
  },
  {
    panda_plant: 1,
    aloe: 4,
    asparagus_fern: 2,
    alocasia: 8,
    banana_tree: 9,
  },
  {
    panda_plant: 1,
    aloe: 10,
    asparagus_fern: 8,
    alocasia: 4,
    banana_tree: 5,
  },
  {
    panda_plant: 1,
    aloe: 2,
    asparagus_fern: 3,
    alocasia: 2,
    banana_tree: 7,
  },
  {
    panda_plant: 5,
    aloe: 3,
    asparagus_fern: 9,
    alocasia: 9,
    banana_tree: 10,
  },
  {
    panda_plant: 2,
    aloe: 7,
    asparagus_fern: 5,
    alocasia: 9,
    banana_tree: 3,
  },
  {
    panda_plant: 10,
    aloe: 6,
    asparagus_fern: 8,
    alocasia: 6,
    banana_tree: 8,
  },
  {
    panda_plant: 1,
    aloe: 4,
    asparagus_fern: 2,
    alocasia: 8,
    banana_tree: 9,
  },
  {
    panda_plant: 1,
    aloe: 10,
    asparagus_fern: 8,
    alocasia: 4,
    banana_tree: 5,
  },
  {
    panda_plant: 1,
    aloe: 2,
    asparagus_fern: 3,
    alocasia: 2,
    banana_tree: 7,
  },
  {
    panda_plant: 5,
    aloe: 3,
    asparagus_fern: 9,
    alocasia: 9,
    banana_tree: 10,
  },
  {
    panda_plant: 2,
    aloe: 7,
    asparagus_fern: 5,
    alocasia: 9,
    banana_tree: 3,
  },
  {
    panda_plant: 10,
    aloe: 6,
    asparagus_fern: 8,
    alocasia: 6,
    banana_tree: 8,
  },
  {
    panda_plant: 9,
    aloe: 7,
    asparagus_fern: 4,
    alocasia: 3,
    banana_tree: 2,
  },
  {
    panda_plant: 10,
    aloe: 6,
    asparagus_fern: 1,
    alocasia: 2,
    banana_tree: 7,
  },
];
